name: "Test and Lint"

on:
  pull_request:
    branches:
      - "**"

env:
  GO_VERSION: 1.19.5

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "${{env.GO_VERSION}}"

      - name: Lint
        run: |
          make lint

  unittest:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "${{ github.event.pull_request.head.sha }}"

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "${{env.GO_VERSION}}"

      - name: go unit tests
        run: |
          make go-unit-test

      - name: Report Success
        run: echo "::set-output name=run_result::success" > run_result
